#!/usr/bin/env python3
"""Original rendered-mesh pixel finish. No generated-image input is used for assets.
Snap native alpha, use one shared 128-tone palette, add authored tiny wear clusters
attached to projected 3D markers. Screenshots are used only for diagnostic probes.
"""
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import json,hashlib
ROOT=Path(__file__).resolve().parents[1]
WEAPONS=['pistol','shotgun','melee']; POSES=['idle','fire','recover','switch']
NN=Image.Resampling.NEAREST
META=json.loads((ROOT/'source/render_metadata.json').read_text())
FONT='/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'
if not Path(FONT).exists(): FONT='/usr/share/fonts/TTF/DejaVuSans.ttf'
def font(n): return ImageFont.truetype(FONT,n)
def checker(w=320,h=180):
 im=Image.new('RGBA',(w,h),'#283640'); d=ImageDraw.Draw(im)
 for y in range(0,h,16):
  for x in range(0,w,16):
   if (x//16+y//16)%2: d.rectangle((x,y,x+15,y+15),fill='#33434D')
 return im
# Shared palette keeps highlights stable across all representative states.
atlas=Image.new('RGB',(320*4,180*3))
for row,w in enumerate(WEAPONS):
 for col,p in enumerate(POSES): atlas.paste(Image.open(ROOT/f'assets/weapons/{w}/raw_{p}.png').convert('RGB'),(col*320,row*180))
palette=atlas.quantize(colors=128,method=Image.Quantize.MEDIANCUT,dither=Image.Dither.NONE)
checks=[]; manifest={'stage':'Representative prototype weapon production; gameplay quality review pending','method':'Original authored Godot meshes rendered locally, then controlled native pixel finish','imagegen_used':False,'imported_models':False,'source':['source/render.gd','source/render.tscn','source/project.godot','source/finish_sprites.py'],'godot':'4.7.2.stable.official.ed1daf0bf','native_size':[320,180],'held_view_anchor':[160,180],'texture_filter':'nearest','mipmaps':False,'palette_method':'One shared 128-tone render-derived palette, plus a few explicit wear inks','weapons':[]}
for w in WEAPONS:
 frames=[]
 for p in POSES:
  raw=Image.open(ROOT/f'assets/weapons/{w}/raw_{p}.png').convert('RGBA'); alpha=raw.getchannel('A').point(lambda a:255 if a>=128 else 0)
  finished=raw.convert('RGB').quantize(palette=palette,dither=Image.Dither.NONE).convert('RGBA'); finished.putalpha(alpha)
  # Hand-authored tiny highlight/shadow pairs on actual metal face markers.
  changed=0
  for name,point in META[w][p]['cleanup_markers'].items():
   if name in ['muzzle','latch','safety']: continue
   x,y=point
   pixels=[(x,y,'#9BAEB7'),(x+1,y,'#788D99'),(x,y+1,'#25313C')]
   if name in ['slide_scratch','receiver_wear']: pixels.append((x+2,y-1,'#728895'))
   for xx,yy,color in pixels:
    if 0<=xx<320 and 0<=yy<180 and alpha.getpixel((xx,yy))==255:
     finished.putpixel((xx,yy),tuple(int(color[j:j+2],16) for j in (1,3,5))+(255,)); changed+=1
  # Fully transparent pixels contain zero RGB; avoids import edge fringes.
  pix=finished.load()
  for yy in range(180):
   for xx in range(320):
    if pix[xx,yy][3]==0: pix[xx,yy]=(0,0,0,0)
  dest=ROOT/f'assets/weapons/{w}/{p}.png'; finished.save(dest)
  bbox=list(alpha.getbbox()); colors=len({px[:3] for px in finished.get_flattened_data() if px[3]})
  record={'pose':p,'path':str(dest.relative_to(ROOT)),'size':[320,180],'anchor':[160,180],'muzzle_anchor':META[w][p]['muzzle'],'alpha_bounds':bbox,'cleanup_pixels':changed,'opaque_colors':colors,'sha256':hashlib.sha256(dest.read_bytes()).hexdigest()}
  frames.append(record); checks.append({'weapon':w,**record,'alpha_extrema':list(alpha.getextrema()),'binary_alpha':set(alpha.get_flattened_data())=={0,255}})
 manifest['weapons'].append({'id':w,'frames':frames,'states':['idle','fire','recover','switch'],'note':'Representative poses only; not a complete reload/switch/pump animation. Melee fire is a punch extension. Single authoritative shot events must drive display/audio/flash together.'})
# Standalone flash, original pixel clusters with warm directional spokes.
flash=Image.new('RGBA',(64,64)); d=ImageDraw.Draw(flash)
for pts,c in [([(31,3),(35,22),(53,13),(43,28),(61,31),(42,36),(50,52),(34,42),(29,61),(26,42),(9,50),(18,34),(2,28),(22,25),(14,8),(28,20)],'#AF572E'), ([(31,10),(35,26),(48,18),(40,30),(54,32),(39,37),(44,48),(33,40),(29,52),(27,39),(16,44),(23,34),(11,28),(26,28),(20,16),(29,25)],'#EAA752'), ([(29,20),(35,27),(43,29),(40,35),(34,40),(27,38),(22,31)],'#F4D28A'), ([(29,27),(35,27),(38,32),(34,36),(28,35),(25,31)],'#FFF1CD')]: d.polygon(pts,fill=c)
flash.save(ROOT/'assets/weapons/flash.png'); manifest['flash']={'path':'assets/weapons/flash.png','size':[64,64],'anchor':[32,32],'attachment':'Per-frame projected muzzle_anchor, centered on flash anchor','method':'Original authored pixel clusters','lifetime_ms':45,'trigger':'One accepted authoritative shot event; never generated by audio callback.'}
# Contact sheet: exact native frame sizes; equal layout across weapon roles.
sheet=Image.new('RGB',(1280,660),'#111B24'); d=ImageDraw.Draw(sheet)
for row,w in enumerate(WEAPONS):
 for col,p in enumerate(POSES):
  x,y=col*320,row*220
  d.text((x+12,y+10),w.upper()+' / '+p.upper(),font=font(12),fill='#D9E0D9')
  tile=checker(); tile.alpha_composite(Image.open(ROOT/f'assets/weapons/{w}/{p}.png'))
  sheet.paste(tile,(x,y+35))
sheet.save(ROOT/'probes/weapon_contact_sheet.png')
# Honest room-reference overlays, distinct from assets and actual gameplay.
for slug in ['corrupted-biotech','occult-fortress']:
 scene=Image.open(ROOT.parent/f'visual-v2/{slug}/scene_pixel_preview.png').convert('RGBA')
 for w in WEAPONS:
  probe=scene.copy(); weapon=Image.open(ROOT/f'assets/weapons/{w}/idle.png').resize((640,360),NN); probe.alpha_composite(weapon)
  probe.convert('RGB').save(ROOT/f'probes/{slug}_{w}_scale.png')
(ROOT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n'); (ROOT/'verification.json').write_text(json.dumps(checks,indent=2)+'\n')
print('Finished12 RGBA frames, flash, contact sheet, six room-scale reference overlays and manifest.')
