'use client';

import { useEffect, useRef, useState } from 'react';

const MAP = [
  '1111111111111111',
  '1......1.......1',
  '1.111..1.1111..1',
  '1...1..1....1..1',
  '1.1.1..111..1..1',
  '1.1............1',
  '1.111111.1111..1',
  '1...............1',
  '1111111111111111',
];
type Fiend = { x: number; y: number; hp: number; alive: boolean };
type Run = { x: number; y: number; a: number; hp: number; score: number; active: boolean; won: boolean; shot: number; weapon: number; fiends: Fiend[] };
const blank = (): Run => ({ x: 1.55, y: 1.55, a: 0, hp: 100, score: 0, active: false, won: false, shot: 0, weapon: 0, fiends: [{ x: 6.2, y: 2.2, hp: 4, alive: true }, { x: 12.4, y: 3.4, hp: 4, alive: true }, { x: 10.5, y: 7, hp: 4, alive: true }, { x: 4.5, y: 7, hp: 4, alive: true }] });
const solid = (x: number, y: number) => MAP[Math.floor(y)]?.[Math.floor(x)] === '1';
const fix = (a: number) => (a + Math.PI * 2) % (Math.PI * 2);

export function Arena() {
  const canvasRef = useRef<HTMLCanvasElement>(null); const run = useRef(blank()); const keys = useRef(new Set<string>()); const frame = useRef(0); const raf = useRef(0);
  const [hud, setHud] = useState({ hp: 100, score: 0, active: false, won: false, fiends: 4, note: 'The furnace gate is waiting.' });
  const sync = (note?: string) => { const r = run.current; setHud({ hp: Math.max(0, Math.ceil(r.hp)), score: r.score, active: r.active, won: r.won, fiends: r.fiends.filter(f => f.alive).length, note: note ?? (r.fiends.some(f => f.alive) ? 'Find and banish the furnace fiends.' : 'The altar gate is open. Reach the far end.'), }); };
  const start = () => { run.current = blank(); run.current.active = true; sync('Descend into the furnace.'); };
  const fire = () => { const r = run.current; if (!r.active || r.won || r.hp <= 0) return; r.shot = 24; let target: Fiend | undefined; let distance = Infinity; for (const f of r.fiends) { if (!f.alive) continue; const dx = f.x - r.x, dy = f.y - r.y, d = Math.hypot(dx, dy); const da = Math.abs(Math.atan2(Math.sin(Math.atan2(dy, dx) - r.a), Math.cos(Math.atan2(dy, dx) - r.a))); if (da < .15 && d < distance) { target = f; distance = d; } } if (target) { target.hp--; if (!target.hp) { target.alive = false; r.score += 500; sync('Fiend annihilated.'); } else sync('Direct hit.'); } else sync('The blast scorches the dark.'); };
  useEffect(() => { const canvas = canvasRef.current, ctx = canvas?.getContext('2d'); if (!canvas || !ctx) return; const wall = new Image(); wall.src = '/infernal-wall.png'; const floor = new Image(); floor.src = '/infernal-floor.png'; const ceiling = new Image(); ceiling.src = '/infernal-ceiling.png'; const firing = new Image(); firing.src = '/infernal-firing-sheet.png'; const demon = new Image(); demon.src = '/infernal-sentry.png';
    const down = (e: KeyboardEvent) => { const k = e.key.toLowerCase(); if (['w','a','s','d','1','2','3','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k)) e.preventDefault(); keys.current.add(k); if (k === ' ') fire(); if (k === '1' || k === '2' || k === '3') run.current.weapon = Number(k) - 1; }; const up = (e: KeyboardEvent) => keys.current.delete(e.key.toLowerCase()); window.addEventListener('keydown', down); window.addEventListener('keyup', up);
      const draw = () => { const r = run.current, w = canvas.width, h = canvas.height; ctx.fillStyle = '#110205'; ctx.fillRect(0, 0, w, h / 2); const sky = ctx.createLinearGradient(0, 0, 0, h / 2); sky.addColorStop(0, '#160308'); sky.addColorStop(1, '#4b0a0a'); ctx.fillStyle = sky; ctx.fillRect(0, 0, w, h / 2); const floorGradient = ctx.createLinearGradient(0, h / 2, 0, h); floorGradient.addColorStop(0, '#35100d'); floorGradient.addColorStop(1, '#070203'); ctx.fillStyle = floorGradient; ctx.fillRect(0, h / 2, w, h / 2); const tile=220; if (ceiling.complete) for(let y=0;y<h/2;y+=tile) for(let x=0;x<w;x+=tile) ctx.globalAlpha=.36,ctx.drawImage(ceiling,x,y,tile,tile); if (floor.complete) for(let y=h/2;y<h;y+=tile) for(let x=0;x<w;x+=tile) ctx.globalAlpha=.42,ctx.drawImage(floor,x,y,tile,tile); ctx.globalAlpha=1;
      const rays = 240, fov = Math.PI / 3, z: number[] = []; for (let i = 0; i < rays; i++) { const a = r.a - fov / 2 + i / rays * fov; let d = .02; while (d < 18 && !solid(r.x + Math.cos(a) * d, r.y + Math.sin(a) * d)) d += .025; const hitX = r.x + Math.cos(a) * d, hitY = r.y + Math.sin(a) * d, u = Math.abs(Math.abs(Math.cos(a)) > Math.abs(Math.sin(a)) ? hitY - Math.floor(hitY) : hitX - Math.floor(hitX)); const corrected = d * Math.cos(a - r.a), height = Math.min(h * 1.4, 480 / corrected); z[i] = corrected; const x = i * w / rays; const shade = Math.max(22, 210 - corrected * 19); if (wall.complete) { ctx.globalAlpha = Math.max(.18, 1 - corrected / 13); ctx.drawImage(wall, Math.min(1253, Math.floor(u * 1254)), 0, 1, 1254, x, h / 2 - height / 2, w / rays + 1, height); ctx.globalAlpha = 1; ctx.fillStyle = `rgba(31,0,3,${Math.max(0,.73-corrected/20)})`; ctx.fillRect(x, h / 2 - height / 2, w / rays + 1, height); } else { ctx.fillStyle = `rgb(${shade},${Math.floor(shade * .12)},${Math.floor(shade * .1)})`; ctx.fillRect(x, h / 2 - height / 2, w / rays + 1, height); } }
      const targets = r.fiends.filter(f => f.alive).map(f => { const dx = f.x - r.x, dy = f.y - r.y, d = Math.hypot(dx, dy), relative = Math.atan2(Math.sin(Math.atan2(dy, dx) - r.a), Math.cos(Math.atan2(dy, dx) - r.a)); return { f, d, relative }; }).filter(t => Math.abs(t.relative) < fov / 1.7).sort((a,b) => b.d-a.d); for (const t of targets) { const sx = w / 2 + t.relative / fov * w; const size = Math.min(540, 680 / t.d); const col = Math.max(0, Math.min(rays - 1, Math.floor(sx / w * rays))); if (t.d > z[col] + .15) continue; if (demon.complete) ctx.drawImage(demon, sx - size / 2, h / 2 - size * .68, size, size); else { ctx.fillStyle = '#e33a22'; ctx.fillRect(sx-size/4,h/2-size/2,size/2,size); } ctx.fillStyle = '#ff6430'; ctx.fillRect(sx - size / 2, h / 2 - size * .72, size * t.f.hp / 4, 5); }
      ctx.strokeStyle = 'rgba(255,215,170,.75)'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(w/2-12,h/2);ctx.lineTo(w/2+12,h/2);ctx.moveTo(w/2,h/2-12);ctx.lineTo(w/2,h/2+12);ctx.stroke(); if (firing.complete && r.shot) { const fw = firing.width / 4, fh = firing.height / 3, ff = Math.min(3, Math.floor((24 - r.shot) / 6)); ctx.drawImage(firing, ff * fw, r.weapon * fh, fw, fh, w/2-190, h-230, 380, 253); } else { ctx.fillStyle = '#682019'; ctx.fillRect(w/2-70,h-96,140,96); ctx.fillStyle = '#aa321f'; ctx.fillRect(w/2-20,h-130,40,48); } if(r.shot) r.shot--; if (!r.active) { ctx.fillStyle='rgba(6,0,1,.78)';ctx.fillRect(0,0,w,h);ctx.fillStyle='#fff0dd';ctx.textAlign='center';ctx.font='900 46px Arial';ctx.fillText(r.won?'RIFT SEALED':'EYE SORE',w/2,h/2-30);ctx.font='700 17px Arial';ctx.fillStyle='#ff6a3d';ctx.fillText(r.won?'The furnace is silent.':'ORIGINAL OCCULT-INDUSTRIAL DESCENT',w/2,h/2+8); }
      if (r.active && !r.won && r.hp > 0) { const k = keys.current; const turn = (k.has('arrowleft') ? -.052 : 0) + (k.has('arrowright') ? .052 : 0); r.a = fix(r.a + turn); const move = (k.has('w') || k.has('arrowup') ? .052 : 0) + (k.has('s') || k.has('arrowdown') ? -.052 : 0); const strafe = (k.has('a') ? -.047 : 0) + (k.has('d') ? .047 : 0); const nx = r.x + Math.cos(r.a) * move + Math.cos(r.a + Math.PI/2) * strafe, ny = r.y + Math.sin(r.a) * move + Math.sin(r.a + Math.PI/2) * strafe; if (!solid(nx, r.y)) r.x = nx; if (!solid(r.x, ny)) r.y = ny; for (const f of r.fiends) if (f.alive) { const d = Math.hypot(f.x-r.x,f.y-r.y); if (d > .7) { f.x -= (f.x-r.x)/d*.008; f.y -= (f.y-r.y)/d*.008; } else if (frame.current % 35 === 0) r.hp -= 5; } if (!r.fiends.some(f=>f.alive) && r.x > 13.5 && r.y > 6) { r.won=true; r.active=false; r.score += 1500; sync('Rift sealed.'); } if(r.hp<=0){r.active=false;sync('The furnace consumed you.');} if(frame.current++%12===0)sync(); }
      // Keep a small tactical readout in the corner so the exit remains findable.
      const mini = 92, mx = w - mini - 18, my = 18; ctx.fillStyle = 'rgba(7,1,2,.78)'; ctx.fillRect(mx, my, mini, 54); ctx.strokeStyle = 'rgba(255,104,55,.55)'; ctx.strokeRect(mx, my, mini, 54); ctx.fillStyle = 'rgba(255,255,255,.38)'; for (let i=0;i<MAP.length;i++) for (let j=0;j<MAP[i].length;j++) if(MAP[i][j]==='1') ctx.fillRect(mx+j/16*mini,my+i/9*54,mini/16+1,54/9+1); ctx.fillStyle = '#ff5a2f'; ctx.fillRect(mx + r.x / 16 * mini - 2, my + r.y / 9 * 54 - 2, 4, 4); ctx.fillStyle = '#6ed7ff'; ctx.fillRect(mx + 14 / 16 * mini - 2, my + 7 / 9 * 54 - 2, 4, 4);
      raf.current = requestAnimationFrame(draw); }; raf.current=requestAnimationFrame(draw); return()=>{cancelAnimationFrame(raf.current);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);}; }, []);
  const press = (key: string) => { keys.current.add(key); window.setTimeout(() => keys.current.delete(key), 140); };
  return <main className="game-shell"><header className="topbar"><div className="wordmark"><h1>Eye Sore</h1><span>Furnace descent</span></div><div className="top-note">Original first-person action prototype</div></header><section className="game-grid"><div className="arena-frame"><div className="hud"><span>Vitality<br/><strong className={hud.hp<35?'danger':''}>{hud.hp}%</strong></span><span>Fiends<br/><strong>{hud.fiends.toString().padStart(2,'0')}</strong></span><span>Score<br/><strong>{hud.score.toString().padStart(6,'0')}</strong></span></div><canvas ref={canvasRef} width={960} height={600} onPointerDown={fire}/>{!hud.active&&<div className="start-panel"><div><p className="eyebrow">{hud.won?'Rift sealed':'Furnace descent'}</p><h2>{hud.won?'Run complete':'Enter the foundry'}</h2><p>{hud.won?`Final score: ${hud.score}.`:'Clear the fiends, then breach the altar gate. Keep moving: they hunt you.'}</p><button className="launch" onClick={start}>{hud.won?'Descend again':'Start run'}</button></div></div>}</div><aside className="side-panel"><p className="eyebrow">Combat instructions</p><h2>{hud.note}</h2><p>This is an original, fast first-person occult-industrial action prototype with its own levels, art, creatures, and sound direction.</p><div className="rule"/><div className="keys"><div>W/S<span>forward / back</span></div><div>A/D<span>strafe</span></div><div>← / →<span>turn</span></div><div>Click / Space<span>fire</span></div></div><div className="touch-controls"><button className="touch-button" onClick={()=>press('arrowleft')}>↶<span>turn</span></button><button className="touch-button" onClick={()=>press('w')}>↑<span>move</span></button><button className="touch-button" onClick={()=>press('arrowright')}>↷<span>turn</span></button><button className="touch-button" onClick={()=>press('s')}>↓<span>back</span></button><button className="touch-button fire" onClick={fire}>Fire<span>blast</span></button></div></aside></section><footer className="foot">Original game prototype. No Doom artwork, characters, levels, code, music, or other assets are used.</footer></main>;
}
